language: python
python:
  - "3.5"
sudo: false
cache:
  directories:
  - "build"
  - "$HOME/.cache/pip"
install:
  - apt-get -y install genometools
  - python3 setup.py install
script:
  - "./run_tests.sh" 
